version: "3.9"
   
services:
  scrap:
    image: furkanaygur/furkanix_scrap
    volumes:
      - ./webScraping:/code
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"